[package]
name = "logician"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argmin = "0.10.0"
clap = { version = "4.5.30", features = ["derive"] }
fastrand = "2.0.2"
rayon = "1.10.0"
